import json

# One line for json data.
exampleData = """
{"id":"8126253678","type":"PullRequestEvent","actor":{"id":21008895,"login":"omar-limbert","display_login":"omar-limbert
","gravatar_id":"","url":"https://api.github.com/users/omar-limbert","avatar_url":"https://avatars.githubusercontent.com
/u/21008895?"},"repo":{"id":144100170,"name":"devops-at06/OH_Libhoney_Webapp","url":"https://api.github.com/repos/devops
-at06/OH_Libhoney_Webapp"},"payload":{"action":"opened","number":33,"pull_request":{"url":"https://api.github.com/repos/
devops-at06/OH_Libhoney_Webapp/pulls/33","id":209021270,"node_id":"MDExOlB1bGxSZXF1ZXN0MjA5MDIxMjcw","html_url":"https:/
/github.com/devops-at06/OH_Libhoney_Webapp/pull/33","diff_url":"https://github.com/devops-at06/OH_Libhoney_Webapp/pull/3
3.diff","patch_url":"https://github.com/devops-at06/OH_Libhoney_Webapp/pull/33.patch","issue_url":"https://api.github.co
m/repos/devops-at06/OH_Libhoney_Webapp/issues/33","number":33,"state":"open","locked":false,"title":"some fixes on gocd 
config file to run allure reports","user":{"login":"omar-limbert","id":21008895,"node_id":"MDQ6VXNlcjIxMDA4ODk1","avatar
_url":"https://avatars1.githubusercontent.com/u/21008895?v=4","gravatar_id":"","url":"https://api.github.com/users/omar-
limbert","html_url":"https://github.com/omar-limbert","followers_url":"https://api.github.com/users/omar-limbert/followe
rs","following_url":"https://api.github.com/users/omar-limbert/following{/other_user}","gists_url":"https://api.github.c
om/users/omar-limbert/gists{/gist_id}","starred_url":"https://api.github.com/users/omar-limbert/starred{/owner}{/repo}",
"subscriptions_url":"https://api.github.com/users/omar-limbert/subscriptions","organizations_url":"https://api.github.co
m/users/omar-limbert/orgs","repos_url":"https://api.github.com/users/omar-limbert/repos","events_url":"https://api.githu
b.com/users/omar-limbert/events{/privacy}","received_events_url":"https://api.github.com/users/omar-limbert/received_eve
nts","type":"User","site_admin":false},"body":"","created_at":"2018-08-17T01:00:01Z","updated_at":"2018-08-17T01:00:01Z"
,"closed_at":null,"merged_at":null,"merge_commit_sha":null,"assignee":null,"assignees":[],"requested_reviewers":[],"requ
ested_teams":[],"labels":[],"milestone":null,"commits_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/
pulls/33/commits","review_comments_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/pulls/33/comments",
"review_comment_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/pulls/comments{/number}","comments_url
":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/issues/33/comments","statuses_url":"https://api.github.co
m/repos/devops-at06/OH_Libhoney_Webapp/statuses/4c6452365a24a609bba6baad9632a1e3e5ed1e7e","head":{"label":"omar-limbert:
gocd-config-updated","ref":"gocd-config-updated","sha":"4c6452365a24a609bba6baad9632a1e3e5ed1e7e","user":{"login":"omar-
limbert","id":21008895,"node_id":"MDQ6VXNlcjIxMDA4ODk1","avatar_url":"https://avatars1.githubusercontent.com/u/21008895?
v=4","gravatar_id":"","url":"https://api.github.com/users/omar-limbert","html_url":"https://github.com/omar-limbert","fo
llowers_url":"https://api.github.com/users/omar-limbert/followers","following_url":"https://api.github.com/users/omar-li
mbert/following{/other_user}","gists_url":"https://api.github.com/users/omar-limbert/gists{/gist_id}","starred_url":"htt
ps://api.github.com/users/omar-limbert/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/omar-li
mbert/subscriptions","organizations_url":"https://api.github.com/users/omar-limbert/orgs","repos_url":"https://api.githu
b.com/users/omar-limbert/repos","events_url":"https://api.github.com/users/omar-limbert/events{/privacy}","received_even
ts_url":"https://api.github.com/users/omar-limbert/received_events","type":"User","site_admin":false},"repo":{"id":14505
2844,"node_id":"MDEwOlJlcG9zaXRvcnkxNDUwNTI4NDQ=","name":"OH_Libhoney_Webapp","full_name":"omar-limbert/OH_Libhoney_Weba
pp","owner":{"login":"omar-limbert","id":21008895,"node_id":"MDQ6VXNlcjIxMDA4ODk1","avatar_url":"https://avatars1.github
usercontent.com/u/21008895?v=4","gravatar_id":"","url":"https://api.github.com/users/omar-limbert","html_url":"https://g
ithub.com/omar-limbert","followers_url":"https://api.github.com/users/omar-limbert/followers","following_url":"https://a
pi.github.com/users/omar-limbert/following{/other_user}","gists_url":"https://api.github.com/users/omar-limbert/gists{/g
ist_id}","starred_url":"https://api.github.com/users/omar-limbert/starred{/owner}{/repo}","subscriptions_url":"https://a
pi.github.com/users/omar-limbert/subscriptions","organizations_url":"https://api.github.com/users/omar-limbert/orgs","re
pos_url":"https://api.github.com/users/omar-limbert/repos","events_url":"https://api.github.com/users/omar-limbert/event
s{/privacy}","received_events_url":"https://api.github.com/users/omar-limbert/received_events","type":"User","site_admin
":false},"private":false,"html_url":"https://github.com/omar-limbert/OH_Libhoney_Webapp","description":null,"fork":true,
"url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp","forks_url":"https://api.github.com/repos/omar-limb
ert/OH_Libhoney_Webapp/forks","keys_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/keys{/key_id}","c
ollaborators_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/collaborators{/collaborator}","teams_url
":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/teams","hooks_url":"https://api.github.com/repos/omar-li
mbert/OH_Libhoney_Webapp/hooks","issue_events_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/issues/
events{/number}","events_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/events","assignees_url":"htt
ps://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/assignees{/user}","branches_url":"https://api.github.com/repos
/omar-limbert/OH_Libhoney_Webapp/branches{/branch}","tags_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_We
bapp/tags","blobs_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/git/blobs{/sha}","git_tags_url":"ht
tps://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/
omar-limbert/OH_Libhoney_Webapp/git/refs{/sha}","trees_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webap
p/git/trees{/sha}","statuses_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/statuses/{sha}","languag
es_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/languages","stargazers_url":"https://api.github.co
m/repos/omar-limbert/OH_Libhoney_Webapp/stargazers","contributors_url":"https://api.github.com/repos/omar-limbert/OH_Lib
honey_Webapp/contributors","subscribers_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/subscribers",
"subscription_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/subscription","commits_url":"https://ap
i.github.com/repos/omar-limbert/OH_Libhoney_Webapp/commits{/sha}","git_commits_url":"https://api.github.com/repos/omar-l
imbert/OH_Libhoney_Webapp/git/commits{/sha}","comments_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webap
p/comments{/number}","issue_comment_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/issues/comments{/
number}","contents_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/contents/{+path}","compare_url":"h
ttps://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/compare/{base}...{head}","merges_url":"https://api.github.co
m/repos/omar-limbert/OH_Libhoney_Webapp/merges","archive_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Web
app/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/downloads","is
sues_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/issues{/number}","pulls_url":"https://api.github
.com/repos/omar-limbert/OH_Libhoney_Webapp/pulls{/number}","milestones_url":"https://api.github.com/repos/omar-limbert/O
H_Libhoney_Webapp/milestones{/number}","notifications_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp
/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/lab
els{/name}","releases_url":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/releases{/id}","deployments_url
":"https://api.github.com/repos/omar-limbert/OH_Libhoney_Webapp/deployments","created_at":"2018-08-17T00:32:36Z","update
d_at":"2018-08-17T00:55:37Z","pushed_at":"2018-08-17T00:59:52Z","git_url":"git://github.com/omar-limbert/OH_Libhoney_Web
app.git","ssh_url":"git@github.com:omar-limbert/OH_Libhoney_Webapp.git","clone_url":"https://github.com/omar-limbert/OH_
Libhoney_Webapp.git","svn_url":"https://github.com/omar-limbert/OH_Libhoney_Webapp","homepage":null,"size":147,"stargaze
rs_count":0,"watchers_count":0,"language":"Java","has_issues":false,"has_projects":true,"has_downloads":true,"has_wiki":
true,"has_pages":false,"forks_count":0,"mirror_url":null,"archived":false,"open_issues_count":0,"license":null,"forks":0
,"open_issues":0,"watchers":0,"default_branch":"master"}},"base":{"label":"devops-at06:master","ref":"master","sha":"6fe
2a0b0fe1a6b6ae4649dd3c11ef6536a0a4add","user":{"login":"devops-at06","id":41751623,"node_id":"MDEyOk9yZ2FuaXphdGlvbjQxNz
UxNjIz","avatar_url":"https://avatars2.githubusercontent.com/u/41751623?v=4","gravatar_id":"","url":"https://api.github.
com/users/devops-at06","html_url":"https://github.com/devops-at06","followers_url":"https://api.github.com/users/devops-
at06/followers","following_url":"https://api.github.com/users/devops-at06/following{/other_user}","gists_url":"https://a
pi.github.com/users/devops-at06/gists{/gist_id}","starred_url":"https://api.github.com/users/devops-at06/starred{/owner}
{/repo}","subscriptions_url":"https://api.github.com/users/devops-at06/subscriptions","organizations_url":"https://api.g
ithub.com/users/devops-at06/orgs","repos_url":"https://api.github.com/users/devops-at06/repos","events_url":"https://api
.github.com/users/devops-at06/events{/privacy}","received_events_url":"https://api.github.com/users/devops-at06/received
_events","type":"Organization","site_admin":false},"repo":{"id":144100170,"node_id":"MDEwOlJlcG9zaXRvcnkxNDQxMDAxNzA=","
name":"OH_Libhoney_Webapp","full_name":"devops-at06/OH_Libhoney_Webapp","owner":{"login":"devops-at06","id":41751623,"no
de_id":"MDEyOk9yZ2FuaXphdGlvbjQxNzUxNjIz","avatar_url":"https://avatars2.githubusercontent.com/u/41751623?v=4","gravatar
_id":"","url":"https://api.github.com/users/devops-at06","html_url":"https://github.com/devops-at06","followers_url":"ht
tps://api.github.com/users/devops-at06/followers","following_url":"https://api.github.com/users/devops-at06/following{/o
ther_user}","gists_url":"https://api.github.com/users/devops-at06/gists{/gist_id}","starred_url":"https://api.github.com
/users/devops-at06/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/devops-at06/subscriptions",
"organizations_url":"https://api.github.com/users/devops-at06/orgs","repos_url":"https://api.github.com/users/devops-
/repos","events_url":"https://api.github.com/users/devops-at06/events{/privacy}","received_events_url":"https://api.gith
ub.com/users/devops-at06/received_events","type":"Organization","site_admin":false},"private":false,"html_url":"https://
github.com/devops-at06/OH_Libhoney_Webapp","description":null,"fork":false,"url":"https://api.github.com/repos/devops-at
06/OH_Libhoney_Webapp","forks_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/forks","keys_url":"https
://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/keys{/key_id}","collaborators_url":"https://api.github.com/repos/
devops-at06/OH_Libhoney_Webapp/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/devops-at06/OH_Li
bhoney_Webapp/teams","hooks_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/hooks","issue_events_url":
"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/issues/events{/number}","events_url":"https://api.github.co
m/repos/devops-at06/OH_Libhoney_Webapp/events","assignees_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Web
app/assignees{/user}","branches_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/branches{/branch}","ta
gs_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/tags","blobs_url":"https://api.github.com/repos/dev
ops-at06/OH_Libhoney_Webapp/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp
/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/git/refs{/sha}","trees_url"
:"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/git/trees{/sha}","statuses_url":"https://api.github.com/re
pos/devops-at06/OH_Libhoney_Webapp/statuses/{sha}","languages_url":"https://api.github.com/repos/devops-at06/OH_Libhoney
_Webapp/languages","stargazers_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/stargazers","contributo
rs_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/contributors","subscribers_url":"https://api.github
.com/repos/devops-at06/OH_Libhoney_Webapp/subscribers","subscription_url":"https://api.github.com/repos/devops-at06/OH_L
ibhoney_Webapp/subscription","commits_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/commits{/sha}","
git_commits_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/git/commits{/sha}","comments_url":"https:/
/api.github.com/repos/devops-at06/OH_Libhoney_Webapp/comments{/number}","issue_comment_url":"https://api.github.com/repo
s/devops-at06/OH_Libhoney_Webapp/issues/comments{/number}","contents_url":"https://api.github.com/repos/devops-at06/OH_L
ibhoney_Webapp/contents/{+path}","compare_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/compare/{bas
e}...{head}","merges_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/merges","archive_url":"https://ap
i.github.com/repos/devops-at06/OH_Libhoney_Webapp/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/
devops-at06/OH_Libhoney_Webapp/downloads","issues_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/issu
es{/number}","pulls_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/pulls{/number}","milestones_url":"
https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/milestones{/number}","notifications_url":"https://api.github
.com/repos/devops-at06/OH_Libhoney_Webapp/notifications{?since,all,participating}","labels_url":"https://api.github.com/
repos/devops-at06/OH_Libhoney_Webapp/labels{/name}","releases_url":"https://api.github.com/repos/devops-at06/OH_Libhoney
_Webapp/releases{/id}","deployments_url":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/deployments","crea
ted_at":"2018-08-09T04:19:36Z","updated_at":"2018-08-17T00:46:07Z","pushed_at":"2018-08-17T00:46:06Z","git_url":"git://g
ithub.com/devops-at06/OH_Libhoney_Webapp.git","ssh_url":"git@github.com:devops-at06/OH_Libhoney_Webapp.git","clone_url":
"https://github.com/devops-at06/OH_Libhoney_Webapp.git","svn_url":"https://github.com/devops-at06/OH_Libhoney_Webapp","h
omepage":null,"size":147,"stargazers_count":0,"watchers_count":0,"language":"Java","has_issues":true,"has_projects":true
,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":1,"mirror_url":null,"archived":false,"open_issues_
count":1,"license":null,"forks":1,"open_issues":1,"watchers":0,"default_branch":"master"}},"_links":{"self":{"href":"htt
ps://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/pulls/33"},"html":{"href":"https://github.com/devops-at06/OH_Li
bhoney_Webapp/pull/33"},"issue":{"href":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/issues/33"},"commen
ts":{"href":"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/issues/33/comments"},"review_comments":{"href":
"https://api.github.com/repos/devops-at06/OH_Libhoney_Webapp/pulls/33/comments"},"review_comment":{"href":"https://api.g
ithub.com/repos/devops-at06/OH_Libhoney_Webapp/pulls/comments{/number}"},"commits":{"href":"https://api.github.com/repos
/devops-at06/OH_Libhoney_Webapp/pulls/33/commits"},"statuses":{"href":"https://api.github.com/repos/devops-at06/OH_Libho
ney_Webapp/statuses/4c6452365a24a609bba6baad9632a1e3e5ed1e7e"}},"author_association":"COLLABORATOR","merged":false,"merg
eable":null,"rebaseable":null,"mergeable_state":"unknown","merged_by":null,"comments":0,"review_comments":0,"maintainer_
can_modify":true,"commits":1,"additions":4,"deletions":22,"changed_files":2}},"public":true,"created_at":"2018-08-17T01:
00:01Z","org":{"id":41751623,"login":"devops-at06","gravatar_id":"","url":"https://api.github.com/orgs/devops-at06","ava
tar_url":"https://avatars.githubusercontent.com/u/41751623?"}}
""".replace('\n', '')

exampleDataJson = json.loads(exampleData)
print(exampleDataJson["payload"]["pull_request"]["head"]["repo"]["languages_url"])
